@startuml Metroid

class Juego 
class Jugador

class GestorVentana
class Pantalla
class PantallaPause
class PantallaJuego
class PantallaInicio
class Menu
class OpcionMenu
class OpcIniciar
class OpcGuardar
class OpcContinuarGuardado
class OpcSalirPausa

class Piso
class PisoSolido
class PisoQuebradiso
class PisoDestruibleMisilRojo
class PisoDestruibleMisilVerde
class PisoDestruibleDash

package PowerUps{
class PowerUp
class TanqueEnergia
class MaruBall
Class VariaSuit
class HighJump
class ScrewAttack

package Proyectiles{
class Proyectil
class Damage
class Beam
class LongBeam
class IceBeam
class WaveBeam
class ShortBeam
class Bombs
class Misil
class MisilRojo
class MisilVerde
}
}

Class Puerta
class PuertaAzul
class PuertaRoja
class PuertaVerde

class Contador
class ControladorMovimiento
class Posicion
class AreaSolida
class Area
class MovimientoEstablecido
class Teclado

class Personaje{
    #vida: int
    #reductorVelocidad: int
    #cuentaRegresiva: int
    +Personaje( posicionX: int, posicionY: int, largoHitBox: int, alturaHitBox: int, inicioSpriteX: int, inicioSpriteY)
    +~Personaje()
    +RecibirDanio(danio: int): void
    +LeerVida(): int
}
class Enemigo{
    #vida: int
    #reductorVelocidad: int
    #cuentaRegresiva: int
    +Enemigo( posicionX: int, posicionY: int, largoHitBox: int, alturaHitBox: int, inicioSpriteX: int, inicioSpriteY)
    +~Enemigo()
    +RecibirDanio(danio: int): void
    +LeerVida(): int
}
class Mellow{
    +Mellow( posicionX: int, posicionY: int)
    +~Mellow()
}
class Hopper
class Swooper
class Swarm
class Flyer
class Crawler{
    +Crawler( posicionX: int, posicionY: int)
    +~Crawler()
}
class Jefe
class Ridley
class MotherBrain
class Kraid
class JugadorSamus{
    +JugadorSamus( posicionX: int, posicionY: int)
    +~JugadorSamus()
} 
class Energia


class ObjetosUsable
class CargaDeEnergia
class CargaDeMisilRojo
class CargaDeMisilVerde

class Atmosfera
class Agua
class Lava 
class Aire
class PisoFalso

class Animacion
class Dibujo{
    - is_open: bool
    - directorio: string
    # textura : sf::Texture
    # sprite : sf::Sprite
    # intRect: sf::IntRect
    # color: sf::Color
    + Dibujo( posicionX: int, posicionY: int, recurso: string , largoHitBox: int, alturaHitBox: int, inicioSpriteX: int, inicioSpriteY: int)
    + Dibujo( recurso: string)
    + MandarSprite(): sf::Sprite
}
class Sonido

class Vector{
    - x: int
    - y: int
    -direccion_x: int
    -direccion_y: int
    +Vector()
    +Vector(x: int, y: int)
    +~Vector()
    +CambiarDireccionY(): void
    +CambiarDireccionX(): void
    +LeerX(): int
    +LeerY(): int
    +LeerDireccionX(): int
    +LeerDireccionY(): int
    +DesplazarX(x : unsigned int  ): void
    +DesplazarY( y: unsigned int ): void
}
class HitBox {
    # xHitBox:unsigned int 
    # yHitBox:unsigned int
    # dxHitBox:unsigned int
    # dyHitBox:unsigned int
    +HitBox(x : unsigned int, y : unsigned int, dx : unsigned int, dy : unsigned int)
    +~HitBox()
    +DetectarColision(hitbox : HitBox): bool
}

Juego "1" *-- "1" Jugador
Juego "1" *-- " 3" Pantalla
Jugador "1" o-- "1" Teclado
Jugador "1" o-- "1" ControladorMovimiento

Dibujo "1" o-- "1" Vector

GestorVentana "1" *-- "1..*"Pantalla
PantallaJuego --|> Pantalla
PantallaPause --|> Pantalla
PantallaJuego "1" *-- "1..*" Atmosfera
PantallaJuego  "1" *-- "1..*" Personaje
PantallaJuego "1" *-- "1..*" Piso
PantallaJuego "1" *-- "0..*" Puerta
PantallaJuego "1" *-- "0..3" Proyectil
PantallaJuego "1" *-- "1" Energia
PantallaJuego "1" *-- "0..2" Misil
PantallaPause "1" *-- "1" Menu

Menu "1"*-- "1..3" OpcionMenu
OpcIniciar --|> OpcionMenu
OpcGuardar --|> OpcionMenu
OpcContinuarGuardado --|> OpcionMenu
OpcSalirPausa --|> OpcionMenu
PantallaInicio "1" *-- "1" Menu
PantallaInicio --|> Pantalla
OpcIniciar --|> OpcionMenu
OpcGuardar --|> OpcionMenu
OpcContinuarGuardado --|> OpcionMenu
OpcSalirPausa --|> OpcionMenu


Piso "1" *-- "1" Animacion
Piso "1" *-- "1" AreaSolida
PisoSolido --|> Piso
PisoDestruibleMisilRojo --|> Piso
PisoDestruibleMisilVerde --|> Piso
PisoDestruibleDash --|> Piso
PisoQuebradiso --|> Piso

PisoDestruibleMisilRojo "1" o-- "1" MisilRojo
PisoDestruibleMisilVerde "1" o-- "1" MisilVerde
PisoQuebradiso "1" o-- "1" Proyectil

JugadorSamus "1" o-- "1..*" PowerUp
TanqueEnergia --|> PowerUp
MaruBall --|> PowerUp
VariaSuit --|> PowerUp
HighJump --|> PowerUp
ScrewAttack --|> PowerUp

Proyectil "1" *-- "1..*" Damage 
Proyectil "1" *-- "2" Animacion
Proyectil --|> PowerUp
Beam --|> Proyectil
Misil --|> Proyectil
Misil "1" *-- "1" Contador
Bombs "1" *-- "1" Contador
MisilRojo --|> Misil
MisilVerde --|> Misil
Bombs --|> Proyectil
ShortBeam --|> Beam
IceBeam --|> Beam
LongBeam --|> Beam
WaveBeam --|> Beam
Misil "1" *-- "1" AreaSolida
Bombs "1" *-- "1" AreaSolida
IceBeam  "1" *-- "1" AreaSolida
ShortBeam "1" *-- "1" AreaSolida
LongBeam "1" *-- "1" AreaSolida
AreaSolida "1" *-- "1..4" Area



ObjetosUsable "1" *-- "1" Animacion
ObjetosUsable "1" *-- "1" Contador
CargaDeEnergia --|> ObjetosUsable
CargaDeMisilRojo --|> ObjetosUsable
CargaDeMisilVerde --|> ObjetosUsable

Atmosfera "1" *-- "1" Animacion 
Atmosfera "1" *-- "1" Posicion
Agua --|> Atmosfera
Lava --|> Atmosfera
Aire --|>Atmosfera
Lava "1" *-- "1" Damage 
PisoFalso --|> Atmosfera

Enemigo --|> Dibujo
Enemigo --|> HitBox
Enemigo --|> Actualizable
Jefe --|> Personaje
JugadorSamus --|> Personaje
ControladorMovimiento "1" o-- "1..*" Personaje
Enemigo  "1" *-- "0,1" ObjetosUsable
JugadorSamus "1" o-- "0..*" ObjetosUsable
Personaje "1" *-- "1" Energia
Energia "1" o-- "0..*" Damage 
Energia "1" *-- "1" Contador
JugadorSamus "1" *-- "1" AreaSolida
Personaje "1" *-- "1.. *" Animacion

Mellow --|> Enemigo
Hopper --|> Enemigo
Swooper --|> Enemigo
Swarm --|> Enemigo
Flyer --|> Enemigo
Crawler --|> Enemigo
MotherBrain --|> Jefe
Ridley --|> Jefe
Kraid --|> Jefe
Enemigo "1" *-- "1" Damage 
Enemigo "1" *-- "1" AreaSolida
Enemigo "1" *-- "1..3" Animacion
Jefe "1" *-- "1" Damage 
Jefe "1" *-- "1" AreaSolida
Jefe "1" *-- "1..*" Animacion 

ControladorMovimiento "1" *-- "1" Posicion
ControladorMovimiento "1" o-- "1..*" AreaSolida
ControladorMovimiento "1" o-- "1..*" MovimientoEstablecido
ControladorMovimiento "1" o-- "1" Teclado
ControladorMovimiento "1" o-- "1..*" Atmosfera

PuertaAzul --|> Puerta
PuertaVerde--|> Puerta
PuertaRoja --|> Puerta

Puerta "1" *-- "1" AreaSolida
PuertaAzul "1" o-- "1" Proyectil
PuertaRoja "1" o-- "1" Misil
PuertaVerde "1" o-- "1" MisilVerde


Animacion "1" *-- "1..*" Dibujo 
Animacion "1" *-- "1..*" Sonido

